services:
  telegram_bot:
    build:
      context: .
      dockerfile: bots/Dockerfile
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - LOG_LEVEL=DEBUG
      - PHOENIX_ENDPOINT=http://phoenix:6006/v1/traces
    volumes:
      - .:/app
    depends_on:
      - phoenix
    restart: unless-stopped

  phoenix:
    image: arizephoenix/phoenix
    ports:
      - "6006:6006"
    environment:
        - PHOENIX_PORT=6006
    volumes:
      - phoenix_data:/data
    restart: unless-stopped

volumes:
  phoenix_data:
